BEGIN TRANSACTION;
insert into tb_subject_test ("ID", "FLAG", "SUBJECT_ID", "UANSWER", "USIGNS", "USCORE", "STATE", "REMARK", "SUBJECT_TYPE") values ('1', '-1', '1', '', NULL, '0', '0', NULL, 1);
insert into tb_subject_test ("ID", "FLAG", "SUBJECT_ID", "UANSWER", "USIGNS", "USCORE", "STATE", "REMARK", "SUBJECT_TYPE") values ('2', '-1', '1', '', NULL, '0', '0', NULL, 6);
insert into tb_subject_test ("ID", "FLAG", "SUBJECT_ID", "UANSWER", "USIGNS", "USCORE", "STATE", "REMARK", "SUBJECT_TYPE") values ('3', '-1', '2', '', NULL, '0', '0', NULL, 6);
insert into tb_subject_test ("ID", "FLAG", "SUBJECT_ID", "UANSWER", "USIGNS", "USCORE", "STATE", "REMARK", "SUBJECT_TYPE") values ('4', '-1', '3', '', NULL, '0', '0', NULL, 6);
insert into tb_subject_test ("ID", "FLAG", "SUBJECT_ID", "UANSWER", "USIGNS", "USCORE", "STATE", "REMARK", "SUBJECT_TYPE") values ('5', '-1', '4', '', NULL, '0', '0', NULL, 6);
insert into tb_subject_test ("ID", "FLAG", "SUBJECT_ID", "UANSWER", "USIGNS", "USCORE", "STATE", "REMARK", "SUBJECT_TYPE") values ('6', '-1', '5', '', NULL, '0', '0', NULL, 6);
insert into tb_subject_test ("ID", "FLAG", "SUBJECT_ID", "UANSWER", "USIGNS", "USCORE", "STATE", "REMARK", "SUBJECT_TYPE") values ('7', '-1', '6', '', NULL, '0', '0', NULL, 6);
insert into tb_subject_test ("ID", "FLAG", "SUBJECT_ID", "UANSWER", "USIGNS", "USCORE", "STATE", "REMARK", "SUBJECT_TYPE") values ('8', '-1', '7', '', NULL, '0', '0', NULL, 6);
insert into tb_subject_test ("ID", "FLAG", "SUBJECT_ID", "UANSWER", "USIGNS", "USCORE", "STATE", "REMARK", "SUBJECT_TYPE") values ('9', '-1', '8', '', NULL, '0', '0', NULL, 6);
COMMIT;
